/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xerris.battleship;

import org.junit.Test;

import xerris.battleship.board.*;

import static org.junit.Assert.*;

public class TestCell {

    @Test
    public void testBoardMethod() {
        Cell cell = new Cell(3,4);
        assertNotNull(cell);
        assertEquals((long)3,(long)cell.getRow());
        
        
    }

	
}
