/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xerris.battleship;

import org.junit.Test;
import xerris.battleship.board.*;
import static org.junit.Assert.*;

public class TestBoard {

    @Test public void testBoardMethod() {
        Board brd = new Board( true);
        //assertTrue("someLibraryMethod should return 'true'", boardClass.bombsomeLibraryMethod());
        
        
    }
}
